os: Windows Server 2012

environment:
  EnableNuGetPackageRestore: true

build_script:
  - "set PATH=%PATH%;C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\"
  - fsi --exec build.fsx Test

artifacts:
  - path: deploy\build\*.zip

test: off
